# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "CF-for-K8s Theme"
license = "MIT"
description = "A theme for the cf-for-k8s.io website"
homepage = "https://cf-for-k8s.io/"
min_version = 0.49
